- .gitignore
- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/action/message_already_up.rb
- lib/vagrant-ovirt4/action/read_ssh_info.rb
- lib/vagrant-ovirt4/action/start_vm.rb
- lib/vagrant-ovirt4/errors.rb
- locales/en.yml
* Assign NIC configuration on startup
* Add support for `vagrant ssh`
* Add missing locales/errors
> Fix NIC creation/startup

- README.md
- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/start_vm.rb
- tools/prepare_redhat_for_box.sh
> Add docs for creating base VM and basic usage

- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/message_powering_up.rb
- locales/en.yml
- spec/vagrant-ovirt4/action/message_powering_up_spec.rb
> Add support for `halt`

- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/is_running.rb
- spec/vagrant-ovirt4/action/is_running_spec.rb
> Add support for `reload`

- README.md
- locales/en.yml
> Add support for `vagrant status` by adding missing translations

- README.md
- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/message_not_suspended.rb
- lib/vagrant-ovirt4/action/message_saving_state.rb
- locales/en.yml
- spec/vagrant-ovirt4/action/message_not_suspended_spec.rb
- spec/vagrant-ovirt4/action/message_saving_state_spec.rb
> Add support for resume

- README.md
- lib/vagrant-ovirt4/action.rb
> Add support for `ssh -c`

- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/snapshot_delete.rb
- lib/vagrant-ovirt4/action/snapshot_list.rb
- lib/vagrant-ovirt4/action/snapshot_save.rb
- lib/vagrant-ovirt4/cap/snapshot_list.rb
- lib/vagrant-ovirt4/cap/snapshot_save.rb
- lib/vagrant-ovirt4/errors.rb
- lib/vagrant-ovirt4/plugin.rb
- locales/en.yml
Resolves #15 
*note* not doing `push` `pop` or `restore` until a use-case comes in.
> Add support for snapshots

- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/sync_folders.rb
- locales/en.yml
> Add support for folder sync

- lib/vagrant-ovirt4/action.rb
> Add support for provision

- lib/vagrant-ovirt4/action.rb
- lib/vagrant-ovirt4/action/set_name_of_domain.rb
> Add support for domain and hostname

- lib/vagrant-ovirt4/action/wait_till_up.rb
> Fix business-as-usual if IP address fails to be published on `up`

- lib/vagrant-ovirt4/action/create_vm.rb
> Fix regex for create failed oVirt exception

- README.md
- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/action/start_vm.rb
- lib/vagrant-ovirt4/config.rb
- spec/vagrant-ovirt4/config_spec.rb
> Add support for cloud_init

- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/config.rb
- spec/vagrant-ovirt4/config_spec.rb
> Bugfix: all the memories

- README.md
- lib/vagrant-ovirt4/action/start_vm.rb
- lib/vagrant-ovirt4/config.rb
- spec/vagrant-ovirt4/config_spec.rb
> Add support for host pinning and placement host

- README.md
- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/start_vm.rb
- lib/vagrant-ovirt4/errors.rb
- locales/en.yml
- tools/prepare_redhat_for_box.sh
Resolves #65 
Not currently working,  see http://lists.ovirt.org/pipermail/devel/2017-February/029559.html
> Add support for dns nameservers/search

- lib/vagrant-ovirt4/action/start_vm.rb
> Add exception handling to vm start

- lib/vagrant-ovirt4/action/create_network_interfaces.rb
Now it works for me on master.
> Fix network lookup

- Gemfile.lock
- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/action/start_vm.rb
- locales/en.yml
- tools/prepare_redhat_for_box.sh
> Add ability to handle zero or multiple network interfaces

- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/start_vm.rb
> Add better handling in start_vm for network_configurations that might be empty

- .kitchen.yml
- README.md
- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/config.rb
- lib/vagrant-ovirt4/errors.rb
- locales/en.yml
- spec/vagrant-ovirt4/config_spec.rb
- test/integration/bios_serial/bios_serial_spec.rb
> Add support for BIOS serial

- lib/vagrant-ovirt4/action.rb
> Added support for handling remote boxes

- lib/vagrant-ovirt4/action/read_ssh_info.rb
- lib/vagrant-ovirt4/action/read_state.rb
- lib/vagrant-ovirt4/action/wait_till_up.rb
Fixed IP address detection for VMs with multiple NICs when one of them has no IP (ONBOOT="no")
fixes #89
> Fixed IP address detection

- lib/vagrant-ovirt4/action/create_network_interfaces.rb
- lib/vagrant-ovirt4/action/start_vm.rb
This pull request contains some changes that make possible to create multiple network interfaces inside VMs. It fix issue #94.
> Allow multiple private_network creation

- README.md
- lib/vagrant-ovirt4/action/create_vm.rb
- lib/vagrant-ovirt4/config.rb
Fixes: #20
Signed-off-by: Ricardo Dias <rdias@suse.com>
> Add support for multiple disks

- locales/en.yml
> add missing translation

- lib/vagrant-ovirt4/action/read_ssh_info.rb
- lib/vagrant-ovirt4/action/read_state.rb
- lib/vagrant-ovirt4/action/wait_till_up.rb
Fixes #136
I'm not fluent in ruby. This is the only ruby project I've ever worked on so there might be a better solution for this. Maybe this will do as a fallback for temporary backwards compatibility. At least it stands out and is easy to drop later.
> fix for backwards compatibility with ovirt 4.3

- Gemfile
- Gemfile.lock
- README.md
- spec/vagrant-ovirt4/config_spec.rb
Also, address some broken tests from #128 (had been suspected according to https://github.com/myoung34/vagrant-ovirt4/pull/128#discussion_r554447290 and https://github.com/myoung34/vagrant-ovirt4/pull/128#discussion_r554447350).
> Facilitate test running
